# warning: do not use ':' inside a string that is double-quotes delimited
# else you will have "script config should be an array of strings or a string"
# see also https://stackoverflow.com/questions/43762269/
#
# warning: a script line (starting with '-') must not start with "

# note: on windows runners, ignore "empty cache key" message because
# we do not use gitlab caching.
# See https://gitlab.com/gitlab-org/gitlab-runner/issues/3253"

# this cmake variable are exposed here so schedule jobs can modify them
variables:
  # cmake superbuild option
  cmake_option_CMAKE_BUILD_TYPE: "Release"

  # two mode exist:
  # - "full": with all optional dependancies
  # - "light": with only the required dependancies
  mode: "full"

  test_blacklist: "TestLidarStream"

  slash_separator: "/"


# this are the 4 stage of the continuous integration, the stage are executed one after another
stages:
  - manual
  - superbuild
  - build
  - test
  - package

# run the job only it modify the source code and if, it's:
#  - a merge request which is not a WIP
#  - a branch ending with "-master"
.only-important:
  only:
    - /[[:alpha:]]*-?master/
    - merge_requests
  except:
    changes:
      - "*.md"
      - "/Documentation/*"
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP:/


# The job are define per OS in a specific file
include:
  - local: '/CI/.gitlab-ci-linux.yml'
#  - local: '/CI/.gitlab-ci-osx.yml' // disable osx job for now
  - local: '/CI/.gitlab-ci-windows.yml'
